version: "3.7"

services:

    example-server:
        hostname: nwnx-server
        image: nwnxee/unified:latest
        env_file: ${PWD-.}/nwserver.env
        stdin_open: true
        tty: true
        volumes:
            - ${PWD-.}/logs:/nwn/run/logs.0
            - ${PWD-.}/:/nwn/home
            - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
        ports:
            - "5121:5121/udp"
